(cl:defpackage play_motion_builder_msgs-srv
  (:use )
  (:export
   "CHANGEJOINTS"
   "<CHANGEJOINTS-REQUEST>"
   "CHANGEJOINTS-REQUEST"
   "<CHANGEJOINTS-RESPONSE>"
   "CHANGEJOINTS-RESPONSE"
   "EDITMOTION"
   "<EDITMOTION-REQUEST>"
   "EDITMOTION-REQUEST"
   "<EDITMOTION-RESPONSE>"
   "EDITMOTION-RESPONSE"
   "LISTJOINTGROUPS"
   "<LISTJOINTGROUPS-REQUEST>"
   "LISTJOINTGROUPS-REQUEST"
   "<LISTJOINTGROUPS-RESPONSE>"
   "LISTJOINTGROUPS-RESPONSE"
   "STOREMOTION"
   "<STOREMOTION-REQUEST>"
   "STOREMOTION-REQUEST"
   "<STOREMOTION-RESPONSE>"
   "STOREMOTION-RESPONSE"
  ))

