// Generated by gencpp from file play_motion_builder_msgs/BuildMotionGoal.msg
// DO NOT EDIT!


#ifndef PLAY_MOTION_BUILDER_MSGS_MESSAGE_BUILDMOTIONGOAL_H
#define PLAY_MOTION_BUILDER_MSGS_MESSAGE_BUILDMOTIONGOAL_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace play_motion_builder_msgs
{
template <class ContainerAllocator>
struct BuildMotionGoal_
{
  typedef BuildMotionGoal_<ContainerAllocator> Type;

  BuildMotionGoal_()
    : motion()  {
    }
  BuildMotionGoal_(const ContainerAllocator& _alloc)
    : motion(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _motion_type;
  _motion_type motion;





  typedef boost::shared_ptr< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> const> ConstPtr;

}; // struct BuildMotionGoal_

typedef ::play_motion_builder_msgs::BuildMotionGoal_<std::allocator<void> > BuildMotionGoal;

typedef boost::shared_ptr< ::play_motion_builder_msgs::BuildMotionGoal > BuildMotionGoalPtr;
typedef boost::shared_ptr< ::play_motion_builder_msgs::BuildMotionGoal const> BuildMotionGoalConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator1> & lhs, const ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator2> & rhs)
{
  return lhs.motion == rhs.motion;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator1> & lhs, const ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace play_motion_builder_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "56c5b2babfc4b27e5a596091bb964bc2";
  }

  static const char* value(const ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x56c5b2babfc4b27eULL;
  static const uint64_t static_value2 = 0x5a596091bb964bc2ULL;
};

template<class ContainerAllocator>
struct DataType< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "play_motion_builder_msgs/BuildMotionGoal";
  }

  static const char* value(const ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# Optional name of the motion, if not empty load this motion\n"
"string motion\n"
;
  }

  static const char* value(const ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.motion);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BuildMotionGoal_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::play_motion_builder_msgs::BuildMotionGoal_<ContainerAllocator>& v)
  {
    s << indent << "motion: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.motion);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAY_MOTION_BUILDER_MSGS_MESSAGE_BUILDMOTIONGOAL_H
