// Generated by gencpp from file play_motion_builder_msgs/BuildMotionResult.msg
// DO NOT EDIT!


#ifndef PLAY_MOTION_BUILDER_MSGS_MESSAGE_BUILDMOTIONRESULT_H
#define PLAY_MOTION_BUILDER_MSGS_MESSAGE_BUILDMOTIONRESULT_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace play_motion_builder_msgs
{
template <class ContainerAllocator>
struct BuildMotionResult_
{
  typedef BuildMotionResult_<ContainerAllocator> Type;

  BuildMotionResult_()
    : ok(false)
    , message()  {
    }
  BuildMotionResult_(const ContainerAllocator& _alloc)
    : ok(false)
    , message(_alloc)  {
  (void)_alloc;
    }



   typedef uint8_t _ok_type;
  _ok_type ok;

   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _message_type;
  _message_type message;





  typedef boost::shared_ptr< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> const> ConstPtr;

}; // struct BuildMotionResult_

typedef ::play_motion_builder_msgs::BuildMotionResult_<std::allocator<void> > BuildMotionResult;

typedef boost::shared_ptr< ::play_motion_builder_msgs::BuildMotionResult > BuildMotionResultPtr;
typedef boost::shared_ptr< ::play_motion_builder_msgs::BuildMotionResult const> BuildMotionResultConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator1> & lhs, const ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator2> & rhs)
{
  return lhs.ok == rhs.ok &&
    lhs.message == rhs.message;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator1> & lhs, const ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace play_motion_builder_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "f6fcb3b1ed8c7743c7fb7d5bcca28513";
  }

  static const char* value(const ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xf6fcb3b1ed8c7743ULL;
  static const uint64_t static_value2 = 0xc7fb7d5bcca28513ULL;
};

template<class ContainerAllocator>
struct DataType< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "play_motion_builder_msgs/BuildMotionResult";
  }

  static const char* value(const ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======\n"
"# True if no issues happened during the action\n"
"bool ok\n"
"# If any error has ocurred provide information\n"
"string message\n"
;
  }

  static const char* value(const ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.ok);
      stream.next(m.message);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct BuildMotionResult_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::play_motion_builder_msgs::BuildMotionResult_<ContainerAllocator>& v)
  {
    s << indent << "ok: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.ok);
    s << indent << "message: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.message);
  }
};

} // namespace message_operations
} // namespace ros

#endif // PLAY_MOTION_BUILDER_MSGS_MESSAGE_BUILDMOTIONRESULT_H
