// Generated by gencpp from file play_motion_builder_msgs/ChangeJoints.msg
// DO NOT EDIT!


#ifndef PLAY_MOTION_BUILDER_MSGS_MESSAGE_CHANGEJOINTS_H
#define PLAY_MOTION_BUILDER_MSGS_MESSAGE_CHANGEJOINTS_H

#include <ros/service_traits.h>


#include <play_motion_builder_msgs/ChangeJointsRequest.h>
#include <play_motion_builder_msgs/ChangeJointsResponse.h>


namespace play_motion_builder_msgs
{

struct ChangeJoints
{

typedef ChangeJointsRequest Request;
typedef ChangeJointsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ChangeJoints
} // namespace play_motion_builder_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::play_motion_builder_msgs::ChangeJoints > {
  static const char* value()
  {
    return "80789d75311b0b87f8012fc3ec0415aa";
  }

  static const char* value(const ::play_motion_builder_msgs::ChangeJoints&) { return value(); }
};

template<>
struct DataType< ::play_motion_builder_msgs::ChangeJoints > {
  static const char* value()
  {
    return "play_motion_builder_msgs/ChangeJoints";
  }

  static const char* value(const ::play_motion_builder_msgs::ChangeJoints&) { return value(); }
};


// service_traits::MD5Sum< ::play_motion_builder_msgs::ChangeJointsRequest> should match
// service_traits::MD5Sum< ::play_motion_builder_msgs::ChangeJoints >
template<>
struct MD5Sum< ::play_motion_builder_msgs::ChangeJointsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::play_motion_builder_msgs::ChangeJoints >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::ChangeJointsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::play_motion_builder_msgs::ChangeJointsRequest> should match
// service_traits::DataType< ::play_motion_builder_msgs::ChangeJoints >
template<>
struct DataType< ::play_motion_builder_msgs::ChangeJointsRequest>
{
  static const char* value()
  {
    return DataType< ::play_motion_builder_msgs::ChangeJoints >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::ChangeJointsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::play_motion_builder_msgs::ChangeJointsResponse> should match
// service_traits::MD5Sum< ::play_motion_builder_msgs::ChangeJoints >
template<>
struct MD5Sum< ::play_motion_builder_msgs::ChangeJointsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::play_motion_builder_msgs::ChangeJoints >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::ChangeJointsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::play_motion_builder_msgs::ChangeJointsResponse> should match
// service_traits::DataType< ::play_motion_builder_msgs::ChangeJoints >
template<>
struct DataType< ::play_motion_builder_msgs::ChangeJointsResponse>
{
  static const char* value()
  {
    return DataType< ::play_motion_builder_msgs::ChangeJoints >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::ChangeJointsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLAY_MOTION_BUILDER_MSGS_MESSAGE_CHANGEJOINTS_H
