// Generated by gencpp from file play_motion_builder_msgs/EditMotion.msg
// DO NOT EDIT!


#ifndef PLAY_MOTION_BUILDER_MSGS_MESSAGE_EDITMOTION_H
#define PLAY_MOTION_BUILDER_MSGS_MESSAGE_EDITMOTION_H

#include <ros/service_traits.h>


#include <play_motion_builder_msgs/EditMotionRequest.h>
#include <play_motion_builder_msgs/EditMotionResponse.h>


namespace play_motion_builder_msgs
{

struct EditMotion
{

typedef EditMotionRequest Request;
typedef EditMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct EditMotion
} // namespace play_motion_builder_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::play_motion_builder_msgs::EditMotion > {
  static const char* value()
  {
    return "85e84c3afe79c9be731c7f83946f6b7b";
  }

  static const char* value(const ::play_motion_builder_msgs::EditMotion&) { return value(); }
};

template<>
struct DataType< ::play_motion_builder_msgs::EditMotion > {
  static const char* value()
  {
    return "play_motion_builder_msgs/EditMotion";
  }

  static const char* value(const ::play_motion_builder_msgs::EditMotion&) { return value(); }
};


// service_traits::MD5Sum< ::play_motion_builder_msgs::EditMotionRequest> should match
// service_traits::MD5Sum< ::play_motion_builder_msgs::EditMotion >
template<>
struct MD5Sum< ::play_motion_builder_msgs::EditMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::play_motion_builder_msgs::EditMotion >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::EditMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::play_motion_builder_msgs::EditMotionRequest> should match
// service_traits::DataType< ::play_motion_builder_msgs::EditMotion >
template<>
struct DataType< ::play_motion_builder_msgs::EditMotionRequest>
{
  static const char* value()
  {
    return DataType< ::play_motion_builder_msgs::EditMotion >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::EditMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::play_motion_builder_msgs::EditMotionResponse> should match
// service_traits::MD5Sum< ::play_motion_builder_msgs::EditMotion >
template<>
struct MD5Sum< ::play_motion_builder_msgs::EditMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::play_motion_builder_msgs::EditMotion >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::EditMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::play_motion_builder_msgs::EditMotionResponse> should match
// service_traits::DataType< ::play_motion_builder_msgs::EditMotion >
template<>
struct DataType< ::play_motion_builder_msgs::EditMotionResponse>
{
  static const char* value()
  {
    return DataType< ::play_motion_builder_msgs::EditMotion >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::EditMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLAY_MOTION_BUILDER_MSGS_MESSAGE_EDITMOTION_H
