// Generated by gencpp from file play_motion_builder_msgs/ListJointGroups.msg
// DO NOT EDIT!


#ifndef PLAY_MOTION_BUILDER_MSGS_MESSAGE_LISTJOINTGROUPS_H
#define PLAY_MOTION_BUILDER_MSGS_MESSAGE_LISTJOINTGROUPS_H

#include <ros/service_traits.h>


#include <play_motion_builder_msgs/ListJointGroupsRequest.h>
#include <play_motion_builder_msgs/ListJointGroupsResponse.h>


namespace play_motion_builder_msgs
{

struct ListJointGroups
{

typedef ListJointGroupsRequest Request;
typedef ListJointGroupsResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct ListJointGroups
} // namespace play_motion_builder_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::play_motion_builder_msgs::ListJointGroups > {
  static const char* value()
  {
    return "9fdaed4e1eb95768801699335d06285a";
  }

  static const char* value(const ::play_motion_builder_msgs::ListJointGroups&) { return value(); }
};

template<>
struct DataType< ::play_motion_builder_msgs::ListJointGroups > {
  static const char* value()
  {
    return "play_motion_builder_msgs/ListJointGroups";
  }

  static const char* value(const ::play_motion_builder_msgs::ListJointGroups&) { return value(); }
};


// service_traits::MD5Sum< ::play_motion_builder_msgs::ListJointGroupsRequest> should match
// service_traits::MD5Sum< ::play_motion_builder_msgs::ListJointGroups >
template<>
struct MD5Sum< ::play_motion_builder_msgs::ListJointGroupsRequest>
{
  static const char* value()
  {
    return MD5Sum< ::play_motion_builder_msgs::ListJointGroups >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::ListJointGroupsRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::play_motion_builder_msgs::ListJointGroupsRequest> should match
// service_traits::DataType< ::play_motion_builder_msgs::ListJointGroups >
template<>
struct DataType< ::play_motion_builder_msgs::ListJointGroupsRequest>
{
  static const char* value()
  {
    return DataType< ::play_motion_builder_msgs::ListJointGroups >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::ListJointGroupsRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::play_motion_builder_msgs::ListJointGroupsResponse> should match
// service_traits::MD5Sum< ::play_motion_builder_msgs::ListJointGroups >
template<>
struct MD5Sum< ::play_motion_builder_msgs::ListJointGroupsResponse>
{
  static const char* value()
  {
    return MD5Sum< ::play_motion_builder_msgs::ListJointGroups >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::ListJointGroupsResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::play_motion_builder_msgs::ListJointGroupsResponse> should match
// service_traits::DataType< ::play_motion_builder_msgs::ListJointGroups >
template<>
struct DataType< ::play_motion_builder_msgs::ListJointGroupsResponse>
{
  static const char* value()
  {
    return DataType< ::play_motion_builder_msgs::ListJointGroups >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::ListJointGroupsResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLAY_MOTION_BUILDER_MSGS_MESSAGE_LISTJOINTGROUPS_H
