// Generated by gencpp from file play_motion_builder_msgs/StoreMotion.msg
// DO NOT EDIT!


#ifndef PLAY_MOTION_BUILDER_MSGS_MESSAGE_STOREMOTION_H
#define PLAY_MOTION_BUILDER_MSGS_MESSAGE_STOREMOTION_H

#include <ros/service_traits.h>


#include <play_motion_builder_msgs/StoreMotionRequest.h>
#include <play_motion_builder_msgs/StoreMotionResponse.h>


namespace play_motion_builder_msgs
{

struct StoreMotion
{

typedef StoreMotionRequest Request;
typedef StoreMotionResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct StoreMotion
} // namespace play_motion_builder_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::play_motion_builder_msgs::StoreMotion > {
  static const char* value()
  {
    return "878970372ab61349ab9cd98973b0ae49";
  }

  static const char* value(const ::play_motion_builder_msgs::StoreMotion&) { return value(); }
};

template<>
struct DataType< ::play_motion_builder_msgs::StoreMotion > {
  static const char* value()
  {
    return "play_motion_builder_msgs/StoreMotion";
  }

  static const char* value(const ::play_motion_builder_msgs::StoreMotion&) { return value(); }
};


// service_traits::MD5Sum< ::play_motion_builder_msgs::StoreMotionRequest> should match
// service_traits::MD5Sum< ::play_motion_builder_msgs::StoreMotion >
template<>
struct MD5Sum< ::play_motion_builder_msgs::StoreMotionRequest>
{
  static const char* value()
  {
    return MD5Sum< ::play_motion_builder_msgs::StoreMotion >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::StoreMotionRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::play_motion_builder_msgs::StoreMotionRequest> should match
// service_traits::DataType< ::play_motion_builder_msgs::StoreMotion >
template<>
struct DataType< ::play_motion_builder_msgs::StoreMotionRequest>
{
  static const char* value()
  {
    return DataType< ::play_motion_builder_msgs::StoreMotion >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::StoreMotionRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::play_motion_builder_msgs::StoreMotionResponse> should match
// service_traits::MD5Sum< ::play_motion_builder_msgs::StoreMotion >
template<>
struct MD5Sum< ::play_motion_builder_msgs::StoreMotionResponse>
{
  static const char* value()
  {
    return MD5Sum< ::play_motion_builder_msgs::StoreMotion >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::StoreMotionResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::play_motion_builder_msgs::StoreMotionResponse> should match
// service_traits::DataType< ::play_motion_builder_msgs::StoreMotion >
template<>
struct DataType< ::play_motion_builder_msgs::StoreMotionResponse>
{
  static const char* value()
  {
    return DataType< ::play_motion_builder_msgs::StoreMotion >::value();
  }
  static const char* value(const ::play_motion_builder_msgs::StoreMotionResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // PLAY_MOTION_BUILDER_MSGS_MESSAGE_STOREMOTION_H
