; Auto-generated. Do not edit!


(cl:in-package play_motion_builder_msgs-msg)


;//! \htmlinclude BuildMotionResult.msg.html

(cl:defclass <BuildMotionResult> (roslisp-msg-protocol:ros-message)
  ((ok
    :reader ok
    :initarg :ok
    :type cl:boolean
    :initform cl:nil)
   (message
    :reader message
    :initarg :message
    :type cl:string
    :initform ""))
)

(cl:defclass BuildMotionResult (<BuildMotionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BuildMotionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BuildMotionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name play_motion_builder_msgs-msg:<BuildMotionResult> is deprecated: use play_motion_builder_msgs-msg:BuildMotionResult instead.")))

(cl:ensure-generic-function 'ok-val :lambda-list '(m))
(cl:defmethod ok-val ((m <BuildMotionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader play_motion_builder_msgs-msg:ok-val is deprecated.  Use play_motion_builder_msgs-msg:ok instead.")
  (ok m))

(cl:ensure-generic-function 'message-val :lambda-list '(m))
(cl:defmethod message-val ((m <BuildMotionResult>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader play_motion_builder_msgs-msg:message-val is deprecated.  Use play_motion_builder_msgs-msg:message instead.")
  (message m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BuildMotionResult>) ostream)
  "Serializes a message object of type '<BuildMotionResult>"
  (cl:write-byte (cl:ldb (cl:byte 8 0) (cl:if (cl:slot-value msg 'ok) 1 0)) ostream)
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'message))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'message))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BuildMotionResult>) istream)
  "Deserializes a message object of type '<BuildMotionResult>"
    (cl:setf (cl:slot-value msg 'ok) (cl:not (cl:zerop (cl:read-byte istream))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'message) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'message) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BuildMotionResult>)))
  "Returns string type for a message object of type '<BuildMotionResult>"
  "play_motion_builder_msgs/BuildMotionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BuildMotionResult)))
  "Returns string type for a message object of type 'BuildMotionResult"
  "play_motion_builder_msgs/BuildMotionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BuildMotionResult>)))
  "Returns md5sum for a message object of type '<BuildMotionResult>"
  "f6fcb3b1ed8c7743c7fb7d5bcca28513")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BuildMotionResult)))
  "Returns md5sum for a message object of type 'BuildMotionResult"
  "f6fcb3b1ed8c7743c7fb7d5bcca28513")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BuildMotionResult>)))
  "Returns full string definition for message of type '<BuildMotionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# True if no issues happened during the action~%bool ok~%# If any error has ocurred provide information~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BuildMotionResult)))
  "Returns full string definition for message of type 'BuildMotionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# True if no issues happened during the action~%bool ok~%# If any error has ocurred provide information~%string message~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BuildMotionResult>))
  (cl:+ 0
     1
     4 (cl:length (cl:slot-value msg 'message))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BuildMotionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'BuildMotionResult
    (cl:cons ':ok (ok msg))
    (cl:cons ':message (message msg))
))
