; Auto-generated. Do not edit!


(cl:in-package play_motion_builder_msgs-msg)


;//! \htmlinclude BuildMotionFeedback.msg.html

(cl:defclass <BuildMotionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass BuildMotionFeedback (<BuildMotionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <BuildMotionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'BuildMotionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name play_motion_builder_msgs-msg:<BuildMotionFeedback> is deprecated: use play_motion_builder_msgs-msg:BuildMotionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <BuildMotionFeedback>) ostream)
  "Serializes a message object of type '<BuildMotionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <BuildMotionFeedback>) istream)
  "Deserializes a message object of type '<BuildMotionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<BuildMotionFeedback>)))
  "Returns string type for a message object of type '<BuildMotionFeedback>"
  "play_motion_builder_msgs/BuildMotionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'BuildMotionFeedback)))
  "Returns string type for a message object of type 'BuildMotionFeedback"
  "play_motion_builder_msgs/BuildMotionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<BuildMotionFeedback>)))
  "Returns md5sum for a message object of type '<BuildMotionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'BuildMotionFeedback)))
  "Returns md5sum for a message object of type 'BuildMotionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<BuildMotionFeedback>)))
  "Returns full string definition for message of type '<BuildMotionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'BuildMotionFeedback)))
  "Returns full string definition for message of type 'BuildMotionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <BuildMotionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <BuildMotionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'BuildMotionFeedback
))
