; Auto-generated. Do not edit!


(cl:in-package play_motion_builder_msgs-msg)


;//! \htmlinclude RunMotionResult.msg.html

(cl:defclass <RunMotionResult> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RunMotionResult (<RunMotionResult>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunMotionResult>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunMotionResult)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name play_motion_builder_msgs-msg:<RunMotionResult> is deprecated: use play_motion_builder_msgs-msg:RunMotionResult instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunMotionResult>) ostream)
  "Serializes a message object of type '<RunMotionResult>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunMotionResult>) istream)
  "Deserializes a message object of type '<RunMotionResult>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunMotionResult>)))
  "Returns string type for a message object of type '<RunMotionResult>"
  "play_motion_builder_msgs/RunMotionResult")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunMotionResult)))
  "Returns string type for a message object of type 'RunMotionResult"
  "play_motion_builder_msgs/RunMotionResult")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunMotionResult>)))
  "Returns md5sum for a message object of type '<RunMotionResult>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunMotionResult)))
  "Returns md5sum for a message object of type 'RunMotionResult"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunMotionResult>)))
  "Returns full string definition for message of type '<RunMotionResult>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunMotionResult)))
  "Returns full string definition for message of type 'RunMotionResult"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunMotionResult>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunMotionResult>))
  "Converts a ROS message object to a list"
  (cl:list 'RunMotionResult
))
