; Auto-generated. Do not edit!


(cl:in-package play_motion_builder_msgs-msg)


;//! \htmlinclude RunMotionFeedback.msg.html

(cl:defclass <RunMotionFeedback> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass RunMotionFeedback (<RunMotionFeedback>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunMotionFeedback>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunMotionFeedback)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name play_motion_builder_msgs-msg:<RunMotionFeedback> is deprecated: use play_motion_builder_msgs-msg:RunMotionFeedback instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunMotionFeedback>) ostream)
  "Serializes a message object of type '<RunMotionFeedback>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunMotionFeedback>) istream)
  "Deserializes a message object of type '<RunMotionFeedback>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunMotionFeedback>)))
  "Returns string type for a message object of type '<RunMotionFeedback>"
  "play_motion_builder_msgs/RunMotionFeedback")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunMotionFeedback)))
  "Returns string type for a message object of type 'RunMotionFeedback"
  "play_motion_builder_msgs/RunMotionFeedback")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunMotionFeedback>)))
  "Returns md5sum for a message object of type '<RunMotionFeedback>"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunMotionFeedback)))
  "Returns md5sum for a message object of type 'RunMotionFeedback"
  "d41d8cd98f00b204e9800998ecf8427e")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunMotionFeedback>)))
  "Returns full string definition for message of type '<RunMotionFeedback>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunMotionFeedback)))
  "Returns full string definition for message of type 'RunMotionFeedback"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunMotionFeedback>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunMotionFeedback>))
  "Converts a ROS message object to a list"
  (cl:list 'RunMotionFeedback
))
