; Auto-generated. Do not edit!


(cl:in-package play_motion_builder_msgs-msg)


;//! \htmlinclude RunMotionActionGoal.msg.html

(cl:defclass <RunMotionActionGoal> (roslisp-msg-protocol:ros-message)
  ((header
    :reader header
    :initarg :header
    :type std_msgs-msg:Header
    :initform (cl:make-instance 'std_msgs-msg:Header))
   (goal_id
    :reader goal_id
    :initarg :goal_id
    :type actionlib_msgs-msg:GoalID
    :initform (cl:make-instance 'actionlib_msgs-msg:GoalID))
   (goal
    :reader goal
    :initarg :goal
    :type play_motion_builder_msgs-msg:RunMotionGoal
    :initform (cl:make-instance 'play_motion_builder_msgs-msg:RunMotionGoal)))
)

(cl:defclass RunMotionActionGoal (<RunMotionActionGoal>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <RunMotionActionGoal>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'RunMotionActionGoal)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name play_motion_builder_msgs-msg:<RunMotionActionGoal> is deprecated: use play_motion_builder_msgs-msg:RunMotionActionGoal instead.")))

(cl:ensure-generic-function 'header-val :lambda-list '(m))
(cl:defmethod header-val ((m <RunMotionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader play_motion_builder_msgs-msg:header-val is deprecated.  Use play_motion_builder_msgs-msg:header instead.")
  (header m))

(cl:ensure-generic-function 'goal_id-val :lambda-list '(m))
(cl:defmethod goal_id-val ((m <RunMotionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader play_motion_builder_msgs-msg:goal_id-val is deprecated.  Use play_motion_builder_msgs-msg:goal_id instead.")
  (goal_id m))

(cl:ensure-generic-function 'goal-val :lambda-list '(m))
(cl:defmethod goal-val ((m <RunMotionActionGoal>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader play_motion_builder_msgs-msg:goal-val is deprecated.  Use play_motion_builder_msgs-msg:goal instead.")
  (goal m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <RunMotionActionGoal>) ostream)
  "Serializes a message object of type '<RunMotionActionGoal>"
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'header) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal_id) ostream)
  (roslisp-msg-protocol:serialize (cl:slot-value msg 'goal) ostream)
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <RunMotionActionGoal>) istream)
  "Deserializes a message object of type '<RunMotionActionGoal>"
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'header) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal_id) istream)
  (roslisp-msg-protocol:deserialize (cl:slot-value msg 'goal) istream)
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<RunMotionActionGoal>)))
  "Returns string type for a message object of type '<RunMotionActionGoal>"
  "play_motion_builder_msgs/RunMotionActionGoal")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'RunMotionActionGoal)))
  "Returns string type for a message object of type 'RunMotionActionGoal"
  "play_motion_builder_msgs/RunMotionActionGoal")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<RunMotionActionGoal>)))
  "Returns md5sum for a message object of type '<RunMotionActionGoal>"
  "c76dae4d7be5d9ae3aa0a8f7ba1d019f")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'RunMotionActionGoal)))
  "Returns md5sum for a message object of type 'RunMotionActionGoal"
  "c76dae4d7be5d9ae3aa0a8f7ba1d019f")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<RunMotionActionGoal>)))
  "Returns full string definition for message of type '<RunMotionActionGoal>"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%RunMotionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: play_motion_builder_msgs/RunMotionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Motion modes~%uint8 RUN_MOTION=0~%uint8 GO_TO_STEP=1~%~%uint8 run_mode~%# Factor by which to slow down the motion (only used if run_mode is RUN_MOTION)~%float32 downshift~%# Step id to which the robot will be moved (only used if run_mode is GO_TO_STEP)~%uint16 step_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'RunMotionActionGoal)))
  "Returns full string definition for message of type 'RunMotionActionGoal"
  (cl:format cl:nil "# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%~%Header header~%actionlib_msgs/GoalID goal_id~%RunMotionGoal goal~%~%================================================================================~%MSG: std_msgs/Header~%# Standard metadata for higher-level stamped data types.~%# This is generally used to communicate timestamped data ~%# in a particular coordinate frame.~%# ~%# sequence ID: consecutively increasing ID ~%uint32 seq~%#Two-integer timestamp that is expressed as:~%# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')~%# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')~%# time-handling sugar is provided by the client library~%time stamp~%#Frame this data is associated with~%string frame_id~%~%================================================================================~%MSG: actionlib_msgs/GoalID~%# The stamp should store the time at which this goal was requested.~%# It is used by an action server when it tries to preempt all~%# goals that were requested before a certain time~%time stamp~%~%# The id provides a way to associate feedback and~%# result message with specific goal requests. The id~%# specified must be unique.~%string id~%~%~%================================================================================~%MSG: play_motion_builder_msgs/RunMotionGoal~%# ====== DO NOT MODIFY! AUTOGENERATED FROM AN ACTION DEFINITION ======~%# Motion modes~%uint8 RUN_MOTION=0~%uint8 GO_TO_STEP=1~%~%uint8 run_mode~%# Factor by which to slow down the motion (only used if run_mode is RUN_MOTION)~%float32 downshift~%# Step id to which the robot will be moved (only used if run_mode is GO_TO_STEP)~%uint16 step_id~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <RunMotionActionGoal>))
  (cl:+ 0
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'header))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal_id))
     (roslisp-msg-protocol:serialization-length (cl:slot-value msg 'goal))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <RunMotionActionGoal>))
  "Converts a ROS message object to a list"
  (cl:list 'RunMotionActionGoal
    (cl:cons ':header (header msg))
    (cl:cons ':goal_id (goal_id msg))
    (cl:cons ':goal (goal msg))
))
